server:
  port: 9001

  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  # web:
  #  resources:
  #    add-mapping: true
  mvc:
    throw-exception-if-no-handler-found: true
    # dispatch-options-request: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpadata
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect

  output:
    ansi:
      enabled: always
  logging:
    level:
      org:
        hibernate:
          type: DEBUG